version: '3'

services:
  server:
    build: ./
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  database:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: 'LemonLoftReservations'
      MYSQL_USER: 'loftuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'